[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gemfury-installer"
version = "0.1"

[project.urls]
GitHub = "https://github.com/d33pster/gemfury-installer"