name: Maintain Structure

on:
    push:
        branches: ["main"]

permissions: write-all

jobs:
    maintain:
        runs-on: ubuntu-latest

        steps:
        - name: Maintain or Create Directory Structure
          uses: d33pster/python-project-structure@v3.6
